### PR TITLE
Add a GraphQL preprocessor for adjusting queries on the fly.

### PR DESCRIPTION
**Pull request by pkaminski**
While GraphQL queries can be parametrized in various ways (variables, directives such as `@include`, type switches, etc.), the spec requires that all queries be completely valid -- even parts that won't be executed.  This means that you if you reference fields not defined in the schema the query will fail validation, which is a problem if you're writing queries that must work with multiple schema versions.

The preprocessor works around this limitation by introducing a syntax to conditionally include/exclude parts of the query based on either the GHE version or the user's currently authorized scopes.  (The latter is not strictly necessary but can be convenient when dealing with type switches.)

The preprocessor syntax is based on GraphQL comments.  This runs the risk of the preprocessor directives being accidentally ignored, but retains compatibility with GraphQL syntax checkers and allows the queries to be pasted into interactive explorers as-is.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/20)

### CODE REVIEW

**Comment by pkaminski** [comment]
This will require a major release since it could technically break if comments happen to match the new syntax.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/20)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[`hubkit.js` line 492 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOiH5H58i_aXk2osNi:-NYOiH5H58i_aXk2osNj:b-ek86qw) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L492)):*
> ```JavaScript
>   Hubkit.prototype.graph = function(query, options) {
>     var self = this;
>     options = options || {};
> ```

Nit: How about`options = Object.assign({}, this.defaultOptions, options)`? Then we don't need the `self` variable, nor the boilerplate to check the default value every time when checking an option.
___
*[`hubkit.js` line 506 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOg7ko51bYze_YyF0N:-NYOg7ko51bYze_YyF0O:b-l5sj8n) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L506)):*
> ```JavaScript
>             }
>             var neededVersion = arg.split('.').map(parseInt);
>             var actualVersion = gheVersion.split('.').map(parseInt);
> ```

Do we want to force the radix being 10? Normally we have ESLint force use to set the radix.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/20)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @snoack)

___
*[`hubkit.js` line 492 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOiH5H58i_aXk2osNi:-NYPEKCvEd_5vWjQdh0t:bj3w8im) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L492)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Nit: How about`options = Object.assign({}, this.defaultOptions, options)`? Then we don't need the `self` variable, nor the boilerplate to check the default value every time when checking an option.
</blockquote></details>

I was being conservative and not messing with `options` as it's passed downstream, and I didn't want to ascertain that an early merge wouldn't have any side-effects later.  How about a separate merged object, though?
___
*[`hubkit.js` line 506 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOg7ko51bYze_YyF0N:-NYPCg8k1_0ssv9ONHi1:bshd7em) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L506)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Do we want to force the radix being 10? Normally we have ESLint force use to set the radix.
</blockquote></details>

I didn't bother because we control the `neededVersion` and I don't think GitHub will do anything crazy with the `actualVersion`.  But yeah, we should probably be safe, even though it's a pain since we don't have access to lambda expressions in this old build system...  Done.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`hubkit.js` line 506 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOg7ko51bYze_YyF0N:-NYPKAyZ7Y-OdetVWs1Z:bfzbm3f) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L506)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Maybe we can factor the expression `x.split('.').map(function(x) {return parseInt(x, 10);})` out to get rid of the duplication?
</blockquote></details>

Eh, I'd rather keep a bit of duplication for now and just convert these into Lodash one-liners when we modernize this code.  (My rule of thumb is that duplicated code is not worth factoring out if it would increase the line count, though of course there are plenty of exceptions.)

**Review by snoack — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/20#-:-NYPNa4UDbxPu2RfjWMy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`hubkit.js` line 506 at r1](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYOg7ko51bYze_YyF0N:-NYPN8xY-tDOJnYG0FFx:b-6xoxti) ([raw file](https://github.com/Reviewable/hubkit/blob/5b93bdd67b5aba1eb644ec195ab28be024209e90/hubkit.js#L506)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Eh, I'd rather keep a bit of duplication for now and just convert these into Lodash one-liners when we modernize this code.  (My rule of thumb is that duplicated code is not worth factoring out if it would increase the line count, though of course there are plenty of exceptions.)
</blockquote></details>

Fair enough. It's the same number of lines though:

```js
function toNumArray(s) {return s.split('.').map(function(x) {return parseInt(x, 10);});}
var neededVersion = toNumArray(arg);
var actualVersion = toNumArray(fullOptions.gheVersion);
```

**Comment by fahhem** [comment]
*[`hubkit.js` line 494 at r2](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYPohfS4qVTSbybAiEJ:-NYPohfTE7lu10Jgy9rx:b-h2bkuq) ([raw file](https://github.com/Reviewable/hubkit/blob/b04aa27863ecd5503481f0309c01854a84e7c9e4/hubkit.js#L494)):*
> ```JavaScript
>     var fullOptions = Object.assign({}, this.defaultOptions, options);
>     query = query.replace(
>       /#(\w+)\s*\(([^)]+)\)\s*\{([\s\S]*?)#\}/g,
> ```

There's no comment or test or anything for this regex. Could you add an example somewhere (even if it's in the PR description)?

**Comment by fahhem** [comment]
*[`hubkit.js` line 494 at r2](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYPohfS4qVTSbybAiEJ:-NYPpOtN3ZF4MFC8Jyhe:b-x8rjx3) ([raw file](https://github.com/Reviewable/hubkit/blob/b04aa27863ecd5503481f0309c01854a84e7c9e4/hubkit.js#L494)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

There's no comment or test or anything for this regex. Could you add an example somewhere (even if it's in the PR description)?
</blockquote></details>

Looks like it's used here: https://reviewable.io/reviews/Reviewable/reviewable-client/729 though that's not available to external users so this feature is effectively undocumented

**Comment by pkaminski** [comment]
*[`hubkit.js` line 494 at r2](https://reviewable.io/reviews/Reviewable/hubkit/20#-NYPohfS4qVTSbybAiEJ:-NYPq7kf-0fP76Kx_qfw:btncwk1) ([raw file](https://github.com/Reviewable/hubkit/blob/b04aa27863ecd5503481f0309c01854a84e7c9e4/hubkit.js#L494)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

Looks like it's used here: https://reviewable.io/reviews/Reviewable/reviewable-client/729 though that's not available to external users so this feature is effectively undocumented
</blockquote></details>

TBH I don't think there *are* external users so I've stopped putting in the effort to document such stuff externally.  But I'll add a quick writeup to the `README`.

**Pull request merged**
