### PR TITLE
Migrate to ESLint Flat configs and use reviewable-configs (hubkit)

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`package.json` line 37 at r1](https://reviewable.io/reviews/Reviewable/hubkit/28#-O7pp9KJ-rM5yJ-eyBxC:-O7pp9KK4FcsQManqxo_:bwxp7ps) ([raw file](https://github.com/Reviewable/hubkit/blob/a31e7b84ea1a6ff2adeb866a4fff77238c244a40/package.json#L37)):*
> ```JSON
>     "eslint": "^8.57.0",
>     "release-it": "15.3.0",
>     "reviewable-configs": "Reviewable/reviewable-configs#init"
> ```

To be updated.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`eslint.config.mjs` line 12 at r1](https://reviewable.io/reviews/Reviewable/hubkit/28#-O7q65n85KUWnLxSlPHZ:-O7q65n85KUWnLxSlPH_:b-bnwja) ([raw file](https://github.com/Reviewable/hubkit/blob/a31e7b84ea1a6ff2adeb866a4fff77238c244a40/eslint.config.mjs#L12)):*
> ```JavaScript
>         axios: true,
>         Promise: false,
>         setTimeout: false
> ```

Is there a `globals` set for "things present in both browsers and Node"?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`eslint.config.mjs` line 12 at r1](https://reviewable.io/reviews/Reviewable/hubkit/28#-O7q65n85KUWnLxSlPHZ:-O7q7oG3-sfwoMVGfaxg:b-ucprkz) ([raw file](https://github.com/Reviewable/hubkit/blob/a31e7b84ea1a6ff2adeb866a4fff77238c244a40/eslint.config.mjs#L12)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Is there a `globals` set for "things present in both browsers and Node"?
</blockquote></details>

You can make one like this:

```js
Object.fromEntries(Object.entries(globals.browser).filter(([name]) => name in globals.node))
```

But since we only rely on two globals provided by the environment, I think explicitly listing them is for one less boilerplate.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`eslint.config.mjs` line 12 at r1](https://reviewable.io/reviews/Reviewable/hubkit/28#-O7q65n85KUWnLxSlPHZ:-O7qYtgJ6NHh2WJZfuun:bfvzjfg) ([raw file](https://github.com/Reviewable/hubkit/blob/a31e7b84ea1a6ff2adeb866a4fff77238c244a40/eslint.config.mjs#L12)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

You can make one like this:

```js
Object.fromEntries(Object.entries(globals.browser).filter(([name]) => name in globals.node))
```

But since we only rely on two globals provided by the environment, I think explicitly listing them is for one less boilerplate.
</blockquote></details>

I agree here, but it would be a nice thing to throw into a `config-isomorphic`.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/hubkit/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`package.json` line 37 at r1](https://reviewable.io/reviews/Reviewable/hubkit/28#-O7pp9KJ-rM5yJ-eyBxC:-O7tyyFO2263jV3rf1Px:b-896fix) ([raw file](https://github.com/Reviewable/hubkit/blob/a31e7b84ea1a6ff2adeb866a4fff77238c244a40/package.json#L37)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

To be updated.
</blockquote></details>

Done.

**Pull request merged**
